/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_thecodebakers_lua_InvokeLua */

#ifndef _Included_br_com_thecodebakers_lua_InvokeLua
#define _Included_br_com_thecodebakers_lua_InvokeLua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_thecodebakers_lua_InvokeLua
 * Method:    execLuaScript
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_thecodebakers_lua_InvokeLua_execLuaScript
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
